# Generated by Django 2.0.1 on 2018-01-23 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_manage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenancelog',
            old_name='c_number',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='tenancelog',
            old_name='s_name',
            new_name='t_fio',
        ),
        migrations.RemoveField(
            model_name='tenancelog',
            name='c_model',
        ),
        migrations.RemoveField(
            model_name='tenancelog',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='tenancelog',
            name='m_name',
        ),
    ]
