# Generated by Django 2.0.1 on 2018-01-24 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_manage', '0002_auto_20180123_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancelog',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db_manage.Car', to_field='car_number', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='end_place',
            field=models.CharField(choices=[('Par', 'Парковый'), ('Bal', 'Балатово'), ('Cro', 'Крохалева'), ('Cnt', 'Центр'), ('Mot', 'Мотовилиха'), ('Zak', 'Закамск')], max_length=3, null=True, verbose_name='Точка возврата'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='start_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата аренды'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='start_place',
            field=models.CharField(choices=[('Par', 'Парковый'), ('Bal', 'Балатово'), ('Cro', 'Крохалева'), ('Cnt', 'Центр'), ('Mot', 'Мотовилиха'), ('Zak', 'Закамск')], max_length=3, null=True, verbose_name='Точка аренды'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='t_fio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='db_manage.Tenant', to_field='sname', verbose_name='ФИО'),
        ),
    ]
