# Generated by Django 2.0.1 on 2018-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_manage', '0003_auto_20180124_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenancelog',
            name='end_dt',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='tenancelog',
            name='start_dt',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата аренды'),
        ),
    ]
